binary_sensor:
- platform: modbus_controller
  modbus_controller_id: modbus_inside_unit
  id: sg_ready_a_active_sensor
  internal: True
  name: "SG-Ready A"
  address: 1211
  register_type: holding
  reuse_previous_range: true
  device_class: running
  web_server: 
    sorting_group_id: diagnostic

- platform: modbus_controller
  modbus_controller_id: modbus_inside_unit
  id: internal_pump_active
  name: "Pomp P0"
  address: 1212
  register_type: holding
  device_class: running
  web_server: 
    sorting_group_id: overview

- platform: modbus_controller
  modbus_controller_id: modbus_inside_unit
  id: external_cool_demand_wired
  internal: True
  name: "Externe koudevraag (bedraad)"
  address: 1213
  register_type: holding
  device_class: running
  web_server: 
    sorting_group_id: diagnostic

- platform: modbus_controller
  modbus_controller_id: modbus_inside_unit
  id: external_heat_demand_wired
  internal: True
  name: "Externe warmtevraag (bedraad)"
  address: 1214
  register_type: holding
  device_class: running
  web_server: 
    sorting_group_id: diagnostic

- platform: modbus_controller
  modbus_controller_id: modbus_inside_unit
  id: sg_ready_b_active_sensor
  internal: True
  name: "SG-Ready B"
  address: 1220
  register_type: holding
  reuse_previous_range: true
  device_class: running
  web_server: 
    sorting_group_id: diagnostic

- platform: modbus_controller
  modbus_controller_id: modbus_inside_unit
  name: "Pomp P1"
  internal: True
  address: 1300
  register_type: holding
  device_class: running

- platform: modbus_controller
  modbus_controller_id: modbus_inside_unit
  name: "Pomp P2"
  internal: True
  address: 1301
  register_type: holding
  device_class: running

- platform: modbus_controller
  modbus_controller_id: modbus_inside_unit
  id: dhw_pump_active_sensor
  name: "Tapwater pomp"
  address: 1302
  register_type: holding
  device_class: running
  web_server: 
    sorting_group_id: overview

- platform: modbus_controller
  modbus_controller_id: modbus_inside_unit
  id: three_way_valve_active_sensor
  name: "3-weg klep"
  address: 1305
  register_type: holding
  device_class: running
  web_server: 
    sorting_group_id: overview

- platform: modbus_controller
  modbus_controller_id: modbus_inside_unit
  id: backup_heater_active_sensor
  name: "Verwarmingselement"
  address: 1309
  register_type: holding
  device_class: running
  web_server: 
    sorting_group_id: overview

- platform: modbus_controller
  modbus_controller_id: modbus_outside_unit
  name: "Fan Low Speed Mode"
  device_class: running
  disabled_by_default: true
  register_type: holding
  address: 2108
  bitmask: 0x1
- platform: modbus_controller
  modbus_controller_id: modbus_outside_unit
  name: "Bodemplaat verwarming"
  id: bottom_heater_active_sensor
  device_class: running
  register_type: holding
  address: 2108
  bitmask: 0x4
  web_server: 
    sorting_group_id: overview

- platform: modbus_controller
  modbus_controller_id: modbus_outside_unit
  name: "Carterverwarming"
  device_class: running
  register_type: holding
  address: 2108
  bitmask: 0x8
  web_server: 
    sorting_group_id: diagnostic

- platform: modbus_controller
  modbus_controller_id: modbus_outside_unit
  name: "Fan Defrost Speed Mode"
  internal: True
  register_type: holding
  address: 2108
  bitmask: 0x10
  web_server: 
    sorting_group_id: diagnostic

- platform: modbus_controller
  modbus_controller_id: modbus_outside_unit
  name: "Fan High Speed Mode"
  device_class: running
  disabled_by_default: true
  register_type: holding
  address: 2108
  bitmask: 0x20
  web_server: 
    sorting_group_id: diagnostic

- platform: modbus_controller
  modbus_controller_id: modbus_outside_unit
  name: "4-weg klep switching"
  device_class: moving
  disabled_by_default: true
  register_type: holding
  address: 2108
  bitmask: 0x40
  web_server: 
    sorting_group_id: diagnostic

- platform: modbus_controller
  modbus_controller_id: modbus_outside_unit
  name: "Expansion Valve Lock"
  device_class: lock
  filters:
    - invert:
  disabled_by_default: true
  register_type: holding
  address: 2108
  bitmask: 0x80
  web_server: 
    sorting_group_id: diagnostic

- platform: modbus_controller
  modbus_controller_id: modbus_outside_unit
  name: "Pump Relay"
  internal: True
  register_type: holding
  address: 2108
  bitmask: 0x800

- platform: modbus_controller
  modbus_controller_id: modbus_outside_unit
  name: "Defrost"
  id: defrost_active_sensor
  device_class: running
  icon: mdi:snowflake
  register_type: holding
  address: 2118
  web_server: 
    sorting_group_id: overview

