select:
- platform: modbus_controller
  modbus_controller_id: modbus_outside_unit
  id: compressor_control_select
  name: "Compressor stand (Buiten)"
  internal: True
  address: 1999
  value_type: S_WORD
  web_server:
    sorting_group_id: manual_control
  optionsmap:
    "0": 0
    "1": 1
    "2": 2
    "3": 3
    "4": 4
    "5": 5
    "6": 6
    "7": 7
    "8": 8
    "9": 9
    "10": 10
- platform: modbus_controller
  modbus_controller_id: modbus_outside_unit
  id: working_mode_switch
  internal: True
  name: "Bedrijfsmodus"
  address: 3999
  on_value: 
    then:
      - lambda: 
          id(modbus_outside_is_online) = true;
      - component.update: current_setpoint
  optionsmap:
    "Standby": 0
    "Koelen": 1
    "Verwarmen": 2
    "Onderhoud": 6

- platform: modbus_controller
  modbus_controller_id: modbus_outside_unit
  id: bottomplate_heater_mode
  name: "Bodemplaat verwarmingsmodus"
  address: 3236
  optionsmap:
    "Onbekend": 0
    "Buitentemperatuur": 1
    "Tijdens defrost": 2
