substitutions:
  device_name: openamber
  device_friendly_name: OpenAmber
  device_project_name: jordi.openamber

external_components:
  - source:
      type: local
      path: openamber

openamber_component:
  id: amber_ctrl
  update_interval: 5s

esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}
  project:
    name: ${device_project_name}
    version: dev
  includes:
    - openamber/controllers/constants.h
    - openamber/controllers/pump_controller.h
    - openamber/controllers/compressor_controller.h
    - openamber/controllers/dhw_controller.h
    - openamber/controllers/openamber_component.h
    - openamber/controllers/heat_cool_controller.h
  on_boot:
    then:
      - if:
          condition:
            - switch.is_on: analytics_enabled_switch
          then:
            - mqtt.enable:

esp32:
  framework:
    type: esp-idf

interval:
  - interval: 5min
    then:
      - if:
         condition:
          - switch.is_on: analytics_enabled_switch
         then:
          - script.execute: send_analytics

logger:
  level: INFO
  baud_rate: 0

api:
  reboot_timeout: 0s

# Broker used to push analytics data (Opt-In)
mqtt:
  broker: mqtt.openamber.nl
  enable_on_boot: false
  username: openamber_write
  password: openamber
  discovery: false
  discover_ip: false
  discovery_retain: false
  log_topic: null
  topic_prefix: null

ota:
  - platform: esphome
  - platform: http_request

http_request:
  buffer_size_tx: 1024

update:
  - platform: http_request
    name: Firmware Update
    source: https://github.com/Jordi1990/openamber/releases/latest/download/openamber.manifest.json

web_server:
  port: 80
  version: 3
  sorting_groups:
    - id: overview
      name: "Overzicht"
      sorting_weight: 0
    - id: general_settings
      name: "Algemene instellingen"
      sorting_weight: 10
    - id: dhw_settings
      name: "Tapwater instellingen"
      sorting_weight: 20
    - id: dhw_schedule_settings
      name: "Tapwater schema instellingen"
      sorting_weight: 30
    - id: heating_settings
      name: "Verwarmingsinstellingen"
      sorting_weight: 40
    - id: temperature_sensors
      name: "Temperatuursensoren"
      sorting_weight: 50
    - id: diagnostic
      name: "Diagnostiek"
      sorting_weight: 60
    - id: error_codes
      name: "Foutcodes"
      sorting_weight: 70
    - id: manual_control
      name: "Handmatige bediening"
      sorting_weight: 80
    - id: config
      name: "Config"
      sorting_weight: 90
wifi:
  ap:
    ssid: "OpenAmber"
    password: "openamber"

captive_portal:    

uart:
  baud_rate: 19200
  parity: EVEN

globals:
  - id: modbus_inside_is_online
    type: bool
    restore_value: no
    initial_value: 'false'
  - id: modbus_outside_is_online
    type: bool
    restore_value: no
    initial_value: 'false'

datetime:
 - platform: template
   id: next_legionella_run
   name: "Volgende legionellapreventie"
   type: datetime
   restore_value: true
   optimistic: true
   initial_value: "2030-01-01 10:00:00"
   entity_category: config
   web_server: 
    sorting_group_id: dhw_settings

 - platform: template
   id: dhw_start_time
   type: time
   name: "Tapwater starttijd"
   optimistic: true
   initial_value: "10:00:00"
   restore_value: true
   entity_category: config
   web_server: 
    sorting_group_id: dhw_schedule_settings

 - platform: template
   id: dhw_end_time
   type: time
   name: "Tapwater eindtijd"
   optimistic: true
   initial_value: "17:00:00"
   restore_value: true
   entity_category: config
   web_server: 
    sorting_group_id: dhw_schedule_settings


# Use SNTP for time so we also have time when not connected to Home Assistant.
time:
  - platform: sntp
    id: my_time

modbus:
  send_wait_time: 500ms

modbus_controller:
- id: modbus_outside_unit
  address: 0x2
  update_interval: 30s
  command_throttle: 500ms
  max_cmd_retries: 3
  on_offline:
    then:
      - lambda: |-
          id(modbus_outside_is_online) = false;
      - logger.log: "Modbus outside unit OFFLINE"
  on_online:
    then:
      - lambda: |-
          id(modbus_outside_is_online) = true;
      - logger.log: "Modbus outside unit ONLINE"
- id: modbus_inside_unit
  address: 0x0B
  update_interval: 30s
  command_throttle: 500ms
  max_cmd_retries: 3
  on_offline:
    then:
      - lambda: |-
          id(modbus_inside_is_online) = false;
      - logger.log: "Modbus inside unit OFFLINE"
  on_online:
    then:
      - lambda: |-
          id(modbus_inside_is_online) = true;
      - logger.log: "Modbus inside unit ONLINE"

climate: !include climates.yaml
sensor: !include sensors.yaml
text_sensor: !include text_sensors.yaml
binary_sensor: !include binary_sensors.yaml
number: !include numbers.yaml
switch: !include switches.yaml
select: !include selects.yaml
script: !include scripts.yaml

output:
  - platform: template
    id: pid_heat_output
    type: float
    write_action:
      - lambda: |-
          id(amber_ctrl).write_heat_pid_value(state);

button:
  - platform: factory_reset
    disabled_by_default: true
    name: Restart with Factory Default Settings
