packages:
 - !include openamber/common/openamber.yaml

esphome:
  project:
    version: dev

esphome:
  project:
    version: dev

esp32:
  board: esp32dev
  framework:
    advanced:
      minimum_chip_revision: "3.1"
    
modbus:
  flow_control_pin: GPIO14

uart:
  rx_pin: GPIO32
  tx_pin: GPIO33

switch:
 - platform: gpio
   pin: GPIO22
   name: "Relais verwarming"
   id: relay_heating
   icon: mdi:electric-switch
   restore_mode: RESTORE_DEFAULT_OFF
   web_server: 
    sorting_group_id: manual_control

 - platform: gpio
   pin: GPIO23
   name: "Relais koelen"
   id: relay_cooling
   icon: mdi:electric-switch
   restore_mode: RESTORE_DEFAULT_OFF
   web_server: 
    sorting_group_id: manual_control

sensor:
  - platform: pulse_counter
    pin: GPIO35
    name: Pulse meter
    id: water_flow_rate
    device_class: volume_flow_rate
    unit_of_measurement: L/min
    filters:
      - lambda: return (x / id(flow_sensor_calibration).state);
    total:
      name: Total pulses
      disabled_by_default: true
      unit_of_measurement: l
      filters:
        - lambda: return x / id(flow_sensor_calibration).state;
        - delta: 1

number:
  - platform: template
    name: Flow sensor calibration
    id: flow_sensor_calibration
    min_value: 1
    max_value: 1000
    initial_value: 476
    mode: box
    step: 1
    restore_value: true
    optimistic: true
    unit_of_measurement: pulses/l
    entity_category: config
    web_server: 
        sorting_group_id: general_settings
