- platform: thermostat
  id: climate_controller
  name: Amber thermostat
  sensor: room_temperature
  set_point_minimum_differential: 4.0

  min_cooling_off_time: 15min
  min_cooling_run_time: 1h # Min 1h run
  min_heating_off_time: 15min
  min_heating_run_time: 1h # Min 1h run
  min_idle_time: 15min
  default_preset: Comfort

  # Hysteresis
  heat_deadband: 0.3
  heat_overrun: 0.2

  cool_deadband: 0.5
  cool_overrun: 3.0

  heat_action: 
    then:
      - logger.log: "Start heating"    
  cool_action: 
    then:
      - logger.log: "Start cooling"    
  idle_action: 
    then:
      - logger.log: "Start idling"

  # Presets
  preset:
    - name: Comfort
      default_target_temperature_low: 20.5 °C
      default_target_temperature_high: 24 °C
  web_server: 
    sorting_group_id: overview

# TODO: Find a way to set PID values from settings and maybe different profiles for heating/cooling/dhw.
- platform: pid
  id: pid_heat_cool_temperature_control
  internal: True
  sensor: heat_cool_temperature_tc
  default_target_temperature: 30°C
  heat_output: pid_heat_output
  cool_output: pid_cool_output
  control_parameters:
    kp: 0.6
    ki: 0.002
    kd: 0.7
  deadband_parameters:
    threshold_low: -1
    threshold_high: 1
    deadband_output_averaging_samples: 6
  visual:
    min_temperature: 10
    max_temperature: 45